
[[rule]]
shortcut 	= "cheating"
rule     	= "^7Do ^1NOT^7 use map bugs / exploits! ^1Cheating is not allowed on ANY server!^7"

[[rule]]
shortcut 	= "sk"
rule    	= "^1NO ^7spawnkilling^9!"

[[rule]]
shortcut 	= "sk-fixed"
rule		= "^7Spawnkill on ^1fixed spawns^7 is ^1NOT allowed^7, with any kind of weapons, on our servers."

[[rule]]
shortcut 	= "sk-capturable"
rule		= "^7Spawnkilling at capturable spawn / flag / command posts ^2is^7 allowed."

[[rule]]
shortcut 	= "spawncamping"
rule		= "^7Spawncamping at the spawnexits is ^1NOT^7 allowed."

[[rule]]
shortcut 	= "mortar"
rule		= "^7Mortaring near an spawn area / spawnexits / flag / command posts is ^1NOT^7 allowed!"

[[rule]]
shortcut 	= "spawnpassing"
rule		= "^7Spawnpassing ^2is^7 allowed. As soon as you get shot at you are allowed to defend yourself by shooting back."

[[rule]]
shortcut 	= "selfkill"
rule		= "^7Selfkilling in battle ^2is^7 allowed, but it will count as a kill for the enemy player."

[[rule]]
shortcut 	= "tk"
rule     	= "^7Teamkilling is ^1NOT^7 allowed and in case of complaints you will be kicked from the server!"

[[rule]]
shortcut 	= "lang"
rule     	= "^1English^7 in main and team chat! If you need to speak in your native language with another player, use PM only!"

[[rule]]
shortcut 	= "chat"
rule     	= "^1NO^7 insulting or swearing! Please respect ^1all^7 the Players and Members!"

[[rule]]
shortcut 	= "spam"
rule     	= "^7Do^1 NOT^7 spam! This includes voice chat, normal chat, and excessive arty spam)."

[[rule]]
shortcut 	= "advert"
rule     	= "^7Do ^1NOT^7 advertise! Advertising on our servers is strictly forbidden!"

[[rule]]
shortcut 	= "push"
rule     	= "^7Do ^1NOT^7 push your ^7team mates!"

[[rule]]
shortcut 	= "level"
rule     	= "^7Do ^1NOT^7 ask for ^7admin levels!"

[[rule]]
shortcut 	= "vote"
rule     	= "^7Do ^1NOT^7 repeat votes!"

[[rule]]
shortcut 	= "respect"
rule		= "^1NO^7 insulting, disrespecting or swearing! This will result in a !mute/!kick/!ban without being warned beforehand."

[[rule]]
shortcut 	= "appeal"
rule     	= "^7When you can't accept how a <=TM=>Member/Admin is acting or managing the game, appeal at www.teammuppet.com!"

[[rule]]
shortcut 	= "game"
rule     	= "^7This is only a game. Game for fun! Have a fun and let others to have a fun too!" 

[[rule]]
shortcut 	= "discussion"
rule     	= "^7Game is for fun and forum for discussion. Let's play!" 