[[rule]]
shortcut = "sk"
rule     = "^1NO ^7spawnkilling^9!"

[[rule]]
shortcut = "tk"
rule     = "^1NO ^7teamkilling^9!"

[[rule]]
shortcut = "tb"
rule     = "^1NO ^7teambleeding^9!"

[[rule]]
shortcut = "xp"
rule     = "^1NO ^7XP whoring^9!"

[[rule]]
shortcut = "lan"
rule     = "^7English ^9in ^7main ^9and ^7team chat^9."

[[rule]]
shortcut = "chat"
rule     = "^1NO ^7insulting ^9or ^7swearing^9!"

[[rule]]
shortcut = "advert"
rule     = "^7Do ^1NOT ^7advertise^9!"

[[rule]]
shortcut = "push"
rule     = "^7Do ^1NOT ^9push your ^7team mates^9!"

[[rule]]
shortcut = "level"
rule     = "^7Do ^1NOT ^9ask for ^7admin levels^9!"

[[rule]]
shortcut = "bug"
rule     = "^7Do ^1NOT ^9use ^7map bugs^9/^7exploits^9!"
